[project]
name = "libris-api-docs"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-git-revision-date-localized-plugin==1.4.6",
    "mkdocs-material==9.6.14",
    "mkdocs-static-i18n==1.3.0",
]
